### PR TITLE
fix(deps): update `marked` dependency

### PR DESCRIPTION
**Pull request by pkurri**
Please merge this to resolve issue with marked as 0.3.19 have security issue

Same as #144

### CODE REVIEW

**Comment by christianalfoni** [comment]
Hi there,

Sorry, but this breaks a lot of tests. We need to review all the code and tests with this version change, which will take a bit of time.

**Review by jimmyandrade — APPROVED** [review]
LGTM

**Comment by greggawatt** [comment]
Is there an update on this?

**Comment by feesh** [comment]
Hi there! I'm interested in this fix to address the vulnerability as well — any sense on when this might be resolved, or is there anything I can do to assist?

**Comment by jimmyandrade** [comment]
Hi @feesh thanks for offering help with this

The PR https://github.com/storybookjs/marksy/pull/89 is similar to this, but it includes some test changes.

The only thing missing was to update yarn.lock instead of package-lock.json.

If you can take a look at PR #89  and run the tests locally to see if everything is OK, it would be a great start 😄 🌈

**Comment by jimmyandrade** [comment]
Closed by #144

**Pull request closed without merging**
