### PR TITLE
fix(deps): resolve 1 vulnerability on the package `marked`

### PR DESCRIPTION
**Pull request by ricnef2121**
resolve 1 vulnerability on the package marked, upgrade at the version 0.8.0

### CODE REVIEW

**Comment by ricnef2121** [comment]
resolve 1 vulnerability on the package marked, upgrade at the version…

**Comment by ricnef2121** [comment]
i have added the update to library marked, because there was in  conflict like a vulnerability

**Comment by ricnef2121** [comment]
i have been work for few minutes

**Comment by AviVahl** [comment]
@armgabrielyan this PR adds a `package-lock.json`, while the project uses `yarn.lock`. might want to decide on one of them, as yarn would warn on that other lock file.

**Comment by johannespfeiffer** [comment]
What is the status of this PR? Is the only thing left to do to remove the `package-lock.json`?

**Comment by loreina** [comment]
hey, is there an update on this PR?

**Review by jimmyandrade — CHANGES_REQUESTED** [review]
This PR adds a `package-lock.json`, while the project uses `yarn.lock`.
Please use `yarn` to apply updates to `yarn.lock` and remove `package-lock.json` file.

**Pull request closed without merging**
