### PR TITLE
fix(deps): updated marked version

### PR DESCRIPTION
**Pull request by Akumzy**
Fix for https://www.npmjs.com/advisories/812

Same as #144

### CODE REVIEW

**Comment by krzysiekhum** [comment]
@ndelangen maybe you should do something with this (and merge for example)? ;)

**Comment by ndelangen** [comment]
@Akumzy storybook no longer uses this package anywhere in 6.0, we're looking to either deprecate it or transfer it to a new owner.

https://www.npmjs.com/package/marksy

**Review by jimmyandrade — APPROVED** [review]
LGTM [but ci failed]

**Comment by jimmyandrade** [comment]
Fixed by #144

**Pull request closed without merging**
